[package]
name = "logdna-client"
version = "0.3.0"
authors = ["Connor Peticca <cjpet10@gmail.com>"]
edition = "2018"
license = "MIT"
description = "wrapper around LogDNA's Ingest API"

[dependencies]
#error handling
quick-error = "1"

#io
hyper = "0.13"
tokio = "0.2"
futures = "0.3"
http = "0.2"
flate2 = "1"

#tls
rustls = "0.18"
rustls-native-certs = "0.4"
hyper-rustls = "0.21"

#utils
chrono = "0.4"

#serailzation
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_urlencoded = "0.5"
