[package]
name = "logdna-client"
version = "0.2.1"
authors = ["Connor Peticca <cjpet10@gmail.com>"]
edition = "2018"
license = "MIT"
description = "wrapper around LogDNA's Ingest API"

[dependencies]
#error handling
quick-error = "1"
#io
hyper = "0.13.0-alpha.2"
tokio = "0.2.0-alpha.5"
futures-preview = "0.3.0-alpha.18"
http = "0.1"
flate2 = "1"
#tls
native-tls = "0.2"
hyper-tls = "0.4.0-alpha.2"
#utils
chrono = "0.4"
#serailzation
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_urlencoded = "0.5"